### ISSUE TITLE
Getting random 403 errors when setting files

### ISSUE THREAD

**Issue by Luxoruus** [netlify/blobs#168]
**Describe the bug**

When setting files with the `set()` function I get random 403 errors that disappear if I re-execute multiple times.

```
BlobsInternalError: Netlify Blobs has generated an internal error (403 status code)
    at _Store.set (Path_to_project\node_modules\@netlify\blobs\dist\main.cjs:489:13)      
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Path_to_project\src\index.ts:50:21
```

**Configuration**

System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 533.23 MB / 7.70 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD

**Comment by NicholasAntidormi** [comment]
Hi, I encountered the same error. @Luxoruus did you find anything useful to understand/solve this?
Thanks!

```
Netlify Blobs has generated an internal error: 403 response
  at _Store.get (./node_modules/@netlify/blobs/dist/main.js:261:13)
```
